apiVersion: v1
kind: Namespace
metadata:
  namespace: k8s-tester
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: k8s-tester
  name: k8s-tester-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: greenstock
  name: greenstock-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVerion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: k8s-tester
  name: k8s-tester-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-tester-sa-rolebinding
  namespace: k8s-tester
subjects:
  - kind: ServiceAccount
    name: k8s-tester-sa
    namespace: k8s-tester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-tester-pod-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-node-reader-rolebinding
subjects:
  - kind: ServiceAccount
    name: k8s-tester-sa
    namespace: k8s-tester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-node-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktester
  namespace: k8s-tester
  labels:
    app: tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktester
  template:
    metadata:
      labels:
        app: ktester
    spec:
      serviceAccountName: k8s-tester-sa
      containers:
        - name: ktester
          image: kubernetes-tester:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8080