apiVersion: v1
kind: Namespace
metadata:
  namespace: k8s-tester
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: k8s-tester
  name: k8s-tester-sa
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-rolebinding
subjects:
  - kind: ServiceAccount
    name: k8s-tester
    apiGroups: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktester
  namespace: k8s-tester
  labels:
    app: tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktester
  template:
    metadata:
      labels:
        app: ktester
    spec:
      containers:
        - name: ktester
          image: kubernetes-tester:0.1
          ports:
            - containerPort: 8080
              hostPort: 8080