apiVersion: v1
kind: Namespace
metadata:
  namespace: k8s-tester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktester
  namespace: k8s-tester
  labels:
    app: tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktester
  template:
    metadata:
      labels:
        app: ktester
    spec:
      containers:
        - name: ktester
          image: kubernetes-tester:0.1
          ports:
            - containerPort: 8080
              hostPort: 8080
